index.js
=> reuse existing canvas for repeated calls

index.js
=> making sure to use int coordinates for all particle paths

index.html, index.js
=> adding origin to the api

README.md
=> adding docs

README.md, index.js
=> adding zIndex option

index.html
=> adding demo page with several live code examples and code editors

test/index.test.js
=> adding test assertions

test/index.test.js
=> less drammatic dialate effect

.travis.yml, test/index.test.js
=> adding travis build

README.md
=> adding jsdelivr info

README.md, src/confetti.js, test/index.test.js
=> adding promises to allow user to know when animation is done

test/index.test.js
=> adding tests for `angle`

.travis.yml, bin/on_failure.sh, test/index.test.js
=> creating the shots folder if it does not already exist

test/index.test.js
=> take confetti images directly from the canvas rather than through puppeteer screenshots

bin/on_failure.sh
=> printing uploaded image urls in green

index.html
=> adding a bunch of meta tags

test/index.test.js
=> allowing both 7 or 8 colors in the default test

src/confetti.js
=> saving wobbleX and wobbleY on the fetti object

src/confetti.js, test/index.test.js
=> handling window resize

index.html, src/confetti.js
Hello
Great library...!  I'm using it on a project of mine and needed to be able to specify my own canvas.  I noticed it is in your backlog so I have added an implementation in this pull request.  Some notes:
- Replaced animationObj with a global map of animation objects
- Lookup is based on the id of the canvas
- User specified canvas _must_ have an id set else an exception is thrown
I've updated the demo page but not added any tests.  I could not get the tests to run on my machine and have limited experience with this stack.
Let me know if you have any comments
Cheers
=> User specified canvas impl

README.md, fixtures/page.html, index.html, src/confetti.js, test/index.test.js
=> WIP: user can supply own canvas by using confetti.create(canvas)

build/build.js, fixtures/page.module.html, package.json, test/index.test.js
=> publishing es module

README.md, src/confetti.js, test/index.test.js
=> adding reset method to immediately stop confetti animation and resolve outstanding promises

src/confetti.js
It's not an option per se, but instead randomly switches the shape of a `fetti` between the default or a circle
=> Adds circle shape to confetti mixture

README.md, index.html, src/confetti.js, test/index.test.js
=> adding `shapes` option, new circle shape

index.html, src/confetti.js
=> polyfill canvas ellipse for IE11

build/build.js
=> remove es6 code form module, because angular 😔

index.html
=> demo anchors for linking to specific demo directly

src/confetti.js, test/ssr.test.js
=> adding support for server-side rendering

src/confetti.js
=> simplifying requestAnimationFrame use, dropping use of prefixed versions

src/confetti.js
=> lib canvas will use the same resize logic as a custom canvas

package.json, src/confetti.js, test/index.test.js
=> animating confetti in a web worker with OffscreenCanvas when possible

src/confetti.js
=> throttle frames to 60fps

fixtures/page.minified.html, package.json, src/confetti.js, test/index.test.js
=> making sure that obfuscation does not break code, adding tests for jsdelivr-like terser usage

src/confetti.js
=> reusing single promise in web worker confetti version, in order to eliminate thread messages once confetti are done

README.md, index.html, src/confetti.js
=> adding configurable gravity

src/confetti.js, test/index.test.js
=> fixing issue with resizing custom canvas when using a worker for rendering

build/serve.js, package.json, src/confetti.js
=> falling back to rendering in the main thread if the worker cannot be created

index.html
=> feat: add light mode to the demo page

src/confetti.js
=> allowing ssr to work for es module as well

README.md, index.html, src/confetti.js
=> adding a drift option to allow confetti to move left/right

src/confetti.js
=> improving animation, limiting very skinny confetti that visibly spin around one of their edges

.github/workflows/ci.yml
=> updating publish step to happen in same job as the build, publishing build output files

README.md
Provide a link to the latest version which uses shapes, keeping it in sync with the documented API.
=> Update CDN link in README.md

src/confetti.js
=> registering only a single resize event

README.md, src/confetti.js, test/index.test.js
=> adding a flat option to render confetti without tilt or wobble

index.html
Added smooth scroll transition
https://github.com/catdad/canvas-confetti/assets/20722868/9787830b-7b7f-45ab-9377-aa9935a328e6
=> Smooth Scroll
